### ISSUE TITLE
server cannot be started in hit-refresh mode

### ISSUE THREAD

**Issue by simonjenga** [yegor256/takes#428]
The Project documentation lists the following command line arguments that should be passed to ```FtCLI``` constructor:
```
--port=1234         Tells the server to listen to TCP port 1234
--lifetime=5000     The server will die in five seconds (useful for integration testing)
--refresh           Run the server in hit-refresh mode
--daemon            Runs the server in Java daemon thread (for integration testing)
--threads=30        Processes incoming HTTP requests in 30 parallel threads
--max-latency=5000  Maximum latency in milliseconds per each request
                    (longer requests will be interrupted)
```

However, in the class ```org.takes.http.Options``` our method implementation that checks if we are in hit-refresh mode is currently implemented as follows:

```
public boolean hitRefresh() {
	return this.map.containsKey("hit-refresh");
}
```

There is an inconsistency between ```this.map.containsKey("hit-refresh");``` and the command line argument ```--refresh```. The will make ```org.takes.http.Options#hitRefresh()``` to always return ```false```

The Latency method ```this.map.get("max-latency");``` is matched well to the command line argument ```--max-latency```

**Comment by davvd** [comment]
@yegor256 please take a look at it and dispatch (see [par.21](http://www.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@simonjenga right, typo fixed in f36296d

**Comment by simonjenga** [comment]
@yegor256 You forgot to make the same change in the example ```App``` where it states:
Then, run it like this:

```$ java -cp take.jar App.class --port=8080 --refresh```

**Comment by yegor256** [comment]
@simonjenga fixed in 95b291d thanks
