### ISSUE TITLE
RqMultipart.Base IOException with very large TXT files.

### ISSUE THREAD

**Issue by CarlosGines** [yegor256/takes#626]
When dealing with requests with very large TXT files [like this one](https://drive.google.com/file/d/0BwYOBDbn-h3fX1ZHVmJJdDhPMy13Y1N3Nlh2OW5JVGxJNUlZ) I get this stack trace (using takes 0.31.3):
```
java.io.IOException: Too many open files in system
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createTempFile(File.java:2024)
	at java.io.File.createTempFile(File.java:2070)
	at org.takes.rq.RqMultipart$Base.make(RqMultipart.java:256)
	at org.takes.rq.RqMultipart$Base.requests(RqMultipart.java:239)
	at org.takes.rq.RqMultipart$Base.<init>(RqMultipart.java:151)
```
There are at least a couple of issues that seeam to be similar: #254 #512.

**Comment by davvd** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@CarlosGines can you please show the code, which will allow us to reproduce this?

**Comment by CarlosGines** [comment]
@yegor256 sure, you can reproduce it with this class:
```
public final class App {
  public static void main(final String... args) throws Exception {
    new FtBasic(
    	new Take() {
    		@Override
    		public Response act(final Request req) {  
    			try {
	    			final Request file = new RqMultipart.Base(req);
    			} catch (Exception e) {
    				e.printStackTrace();
    			}
    			return new RsText("Hello, world!");
    		}
    	},
      	8080
    ).start(Exit.NEVER);
  }
}
```
And this html:
```
<!DOCTYPE html>
<html>
<head>
</head>
<body>
	<form method="post" id="upload" action="http://localhost:8080" enctype="multipart/form-data">
		<fieldset>
			<input id="file-name" name="name" autocomplete="off" placeholder="attachment name..." size="30" maxlength="50">
			<input id="file-binary" name="file" type="file">
			<label for="file-submit"></label>
			<input id="file-submit" type="submit" value="Upload">
		</fieldset>
	</form>
</body>
</html>
```

**Comment by yegor256** [comment]
@CarlosGines and then I have to upload a huge file?

**Comment by original-brownbear** [comment]
@CarlosGines is this even still an issue you can reproduce now that #634 is merged? In my opinion that PR should resolve this situation, since it fixes file descriptors not being released in the `RqMultipart.Base`.

**Comment by CarlosGines** [comment]
@original-brownbear yes, still there!

**Comment by CarlosGines** [comment]
@yegor256 that's right. I provided a huge file to test it, [this one](https://drive.google.com/file/d/0BwYOBDbn-h3fX1ZHVmJJdDhPMy13Y1N3Nlh2OW5JVGxJNUlZ).

**Comment by yegor256** [comment]
@original-brownbear do you think it's a bug in Takes?

**Comment by original-brownbear** [comment]
@yegor256 there certainly was a bug that would show exactly like this, but it should have been resolved by #634, also it should not be reproducible this trivially ( see below ). 
The explanation in #634 eventually turned a little long, so to summarize:
* `org.takes.rq.RqMultipart$Base` opened temp file streames and wrapped them in `CapInputStream`
* `CapInputStream#close` was not correctly implemented causing those to never actually close
* eventually you run out of file descriptors

That being said, if this error is happening in 100% of the cases, even after a clean reboot I can't see how this is Takes fault. Even if it was leaking file descriptors like hell, creating one more temp file right after starting clean should always be possible.

**Comment by original-brownbear** [comment]
@CarlosGines please see above comment, can you reproduce this in 100% of cases on a clean reboot even?

**Comment by CarlosGines** [comment]
@original-brownbear yes, I still reproduce it. You can try it too using the code and the file I provide above.

**Comment by CarlosGines** [comment]
@original-brownbear when you say "clean reboot", is there something special I need to do apart from normal rebooting? Some files I need to delete or something?

**Comment by original-brownbear** [comment]
@CarlosGines nope just restarting your computer :) nothing special.
Two things though :) 

1. You have to convince @yegor256 here, not me. He's the architect in this project, while I'm not even part of the team at this time. I merely offered an explanation as to where this could be coming from. Given that you can reproduce this over and over it appears that explanation is not correct here.

2. Pasting a code snippet like the above is a very bad way of reproducing the issue. If you think about it, It'll probably take in excess of 5 minutes to set this code up, run it and then report back here. I don't think anyone is going to do that really. I suggest simply turning this into an actual test case and linking a branch here. This would clearly prove there is an issue and already add value in form of the test :) ... and again don't prove it to me, prove it to the architect here :)

**Comment by CarlosGines** [comment]
@original-brownbear thank you very much, I will take it into account!

**Comment by CarlosGines** [comment]
@yegor256 is this info already enough to raise the bug?
It is there for sure. The `while` in `RqMultipart.Base.request()` loops forever, because of `RqMultipart.Base.buffer` and the `while` loop in `RqMultipart.Base.copy()`.
I have been trying to catch it in a test, but it is taking me far more than even 30 min.

**Comment by yegor256** [comment]
@CarlosGines OK, let's call it a bug and see what we can do. thanks.

**Comment by davvd** [comment]
@carlosgines since there is no milestone yet I set it to "1.0"

**Comment by davvd** [comment]
@carlosgines thanks a lot for reporting, **15 mins** added to your acc, pmt ID `AP-2BM422107K740383H`

**Comment by davvd** [comment]
@dalifreire please proceed, it's yours

**Comment by exper0** [comment]
@yegor256 @original-brownbear @CarlosGines this is supposed to be fixed in scope of #576

**Comment by dalifreire** [comment]
@davvd @exper0 @yegor256 @original-brownbear @CarlosGines Let me know if I must stop or go ahead in this issue, ok?

**Comment by CarlosGines** [comment]
@dalfire you can test it yourself whether it is fixed or not. Follow the instructions I provide in my comments above.

**Comment by dalifreire** [comment]
@CarlosGines I think I didn't understand the problem. Could you better explain exactly what must be done?

@davvd @yegor256 @exper0 @original-brownbear 30 minutes to implement this task. I think I have not enough knowledge of 'takes' to fix that in this time. It is not enough because the problem is much bigger and requires more work than the slotted time allows.

**Comment by CarlosGines** [comment]
@dalifreire First thing is reproducing it. Get the class I provide above and run as explained in Takes [README.md](https://github.com/yegor256/takes/blob/master/README.md) Then create the html I provide above and upload the file I provide. You must get that exception of "too many files".

Then, before trying to solve it, try to catch it in a test. If you do that, it is probably just enough. Read [here](http://www.yegor256.com/2014/04/12/puzzle-driven-development-by-roles.html#designer-and-programmer) about PDD for more info. I have also mentioned above what I had found so far about the problem, something related to the while loops looping forever.

If there are even more things that you think that you need to understand before doing this, create a new issue where you explain them and ask for a solution (try to be as precise as possible). Then say here that that issue is an impediment for you to solve this task.

I hope this helps you!

**Comment by dalifreire** [comment]
@CarlosGines Thanks for your explanation.

@davvd Please, assign someone else.

**Comment by CarlosGines** [comment]
@davvd I would set #651 as an impediment for this ticket, and solve it before assigning it to anybody.

**Comment by yegor256** [comment]
@davvd assign someone else

**Comment by davvd** [comment]
> @davvd assign someone else

@yegor256 all right, we'll find someone else for this task

**Comment by davvd** [comment]
@triberraar this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions... Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by davvd** [comment]
@triberraar check this ["no obligations principle"](http://www.xdsd.org/2014/04/13/no-obligations-principle.html).. This task is on your name for at least 15 days. If you can't close it within the next 48 hours I will have to assign someone else to it. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck. added -30 to your rating, now it is equal to [-30](http://www.netbout.com/b/36486?open=rating)

**Comment by davvd** [comment]
@triberraar this task is taking too long, I have to change the performer, sorry. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle

-60 added to your rating, at the moment it is: [-150](http://www.netbout.com/b/36486?open=rating)

**Comment by davvd** [comment]
@essobedo the task is yours, please go ahead

**Comment by essobedo** [comment]
@davvd Here is my PR #659 please find a reviewer

**Comment by essobedo** [comment]
@CarlosGines @yegor256 @exper0 @original-brownbear FYI the bug still exists, I've just proposed a PR to fix it

**Comment by davvd** [comment]
> @davvd Here is my PR #659 please find a reviewer

@essobedo OK, got it

**Comment by essobedo** [comment]
@CarlosGines the PR has been merged, you can close the ticket, thx in advance

**Comment by CarlosGines** [comment]
@essobedo thank you, #626 closed.

**Comment by essobedo** [comment]
@davvd the ticket is closed, it is ready for the QA, thx in advance.

**Comment by davvd** [comment]
@ypshenychka please, let us know what do you think about this ticket, according to our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is good here.

**Comment by davvd** [comment]
> @davvd Quality is good here.

@ypshenychka thank you

**Comment by davvd** [comment]
@essobedo I added 10 mins to @ypshenychka (for QA review) in transaction 84077467

**30 mins** sent to your balance (ID `84077497`), many thanks! It took 160 hours and 45 mins.

+30 added to your rating, at the moment it is: [+465](http://www.netbout.com/b/36421?open=rating)
