### ISSUE TITLE
pom.xml:373-377: Upgrade qulice to latest 0.17.x and if...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/takes#880]
The puzzle `837-241b1372` from #837 has to be resolved: 

https://github.com/yegor256/takes/blob/c8f3ef2740506815b9c6398f50fb968462ee17d4/pom.xml#L373-L377

The puzzle was created by Victor Noël on 28-Nov-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#880](https://github.com/yegor256/takes/issues/880) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#880](https://github.com/yegor256/takes/issues/880) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/47cc4d28-bf87-4109-90f3-a8906097cffd); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@0crat wait for teamed/qulice#953 to be fixed

**Comment by 0crat** [comment]
> @0crat wait for teamed/qulice#953 to be fixed ([here](https://github.com/yegor256/takes/issues/880#issuecomment-443526082))

@victornoel The impediment for [#880](https://github.com/yegor256/takes/issues/880) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by paulodamaso** [comment]
@victornoel You can exceptionally set checkstyle `@checkstyle <check> (n lines)` annotation to ignore some check in the next lines, so you should set this if you want to get your ticket moving before https://github.com/teamed/qulice/issues/953 is fixed.

**Comment by victornoel** [comment]
@paulodamaso good point, I completely forgot about that :) thanks!

**Comment by victornoel** [comment]
@paulodamaso the PR is #886, teamed/qulice#953 was fixed :)

**Comment by 0pdd** [comment]
The puzzle `837-241b1372` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#894](https://github.com/yegor256/takes/issues/894) is still not solved.

**Comment by 0crat** [comment]
The job [#880](https://github.com/yegor256/takes/issues/880) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/takes/issues/880#issuecomment-446751839))

@ypshenychka The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/takes/issues/880#issuecomment-446751839))

@ypshenychka The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/takes/issues/880#issuecomment-446751839))

@ypshenychka The project doesn't have enough funds, can't make a payment

**Comment by 0pdd** [comment]
@0pdd the puzzle [#unknown]() is still not solved; solved: [#1128](https://github.com/yegor256/takes/issues/1128).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1719](https://github.com/yegor256/takes/issues/1719) is still not solved; solved: [#894](https://github.com/yegor256/takes/issues/894).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1729](https://github.com/yegor256/takes/issues/1729) is still not solved; solved: [#1719](https://github.com/yegor256/takes/issues/1719), [#894](https://github.com/yegor256/takes/issues/894).

**Comment by 0pdd** [comment]
@0pdd all 3 puzzles are solved here: [#1719](https://github.com/yegor256/takes/issues/1719), [#1729](https://github.com/yegor256/takes/issues/1729), [#894](https://github.com/yegor256/takes/issues/894).
